// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema
// to C++ data binding compiler, in the Proprietary License mode.
// You should have received a proprietary license from Code Synthesis
// Tools CC prior to generating this code. See the license text for
// conditions.
//

/**
 * @file
 * @brief Generated from change_transform.xsd.
 */

#ifndef AOSLCPP_AOSL__CHANGE_TRANSFORM_HPP
#define AOSLCPP_AOSL__CHANGE_TRANSFORM_HPP

// Begin prologue.
//

#include <aoslcpp/common.hpp>

//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (XSD_INT_VERSION != 3030000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#include "aosl/change_transform_forward.hpp"

#include <memory>    // std::auto_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

#include <xsd/cxx/tree/containers-wildcard.hxx>

#ifndef XSD_DONT_INCLUDE_INLINE
#define XSD_DONT_INCLUDE_INLINE

#include "aosl/change.hpp"

#include "aosl/transformation_forward.hpp"

#undef XSD_DONT_INCLUDE_INLINE
#else

#include "aosl/change.hpp"

#include "aosl/transformation_forward.hpp"

#endif // XSD_DONT_INCLUDE_INLINE

/**
 * @brief C++ namespace for the %artofsequence.org/aosl/1.0
 * schema namespace.
 */
namespace aosl
{
  /**
   * @brief Class corresponding to the %change_transform schema type.
   *
   * Change that will modify the geometric state of the object
   * by applying one or several geometric transformations.
   * This change cannot be applied to Objects that don't have spatial
   * properties.
   * Each transformation will be applied in the order of appearance in the
   * file.
   *
   * @nosubgrouping
   */
  class Change_transform: public ::aosl::Change
  {
    public:
    /**
     * @name relative
     *
     * @brief Accessor and modifier functions for the %relative
     * sequence element.
     *
     * Geometric transformation to apply to the Object graphic properties.
     * This imply that the object will be moved and/or scaled and/or rotated
     * relatively to it's current graphic state.
     */
    //@{

    /**
     * @brief Element type.
     */
    typedef ::aosl::Transformation RelativeType;

    /**
     * @brief Element sequence container type.
     */
    typedef ::xsd::cxx::tree::sequence< RelativeType > RelativeSequence;

    /**
     * @brief Element iterator type.
     */
    typedef RelativeSequence::iterator RelativeIterator;

    /**
     * @brief Element constant iterator type.
     */
    typedef RelativeSequence::const_iterator RelativeConstIterator;

    /**
     * @brief Element traits type.
     */
    typedef ::xsd::cxx::tree::traits< RelativeType, char > RelativeTraits;

    /**
     * @brief Return a read-only (constant) reference to the element
     * sequence.
     *
     * @return A constant reference to the sequence container.
     */
    const RelativeSequence&
    relative () const;

    /**
     * @brief Return a read-write reference to the element sequence.
     *
     * @return A reference to the sequence container.
     */
    RelativeSequence&
    relative ();

    /**
     * @brief Copy elements from a given sequence.
     *
     * @param s A sequence to copy elements from.
     *
     * For each element in @a s this function makes a copy and adds it 
     * to the sequence. Note that this operation completely changes the 
     * sequence and all old elements will be lost.
     */
    void
    relative (const RelativeSequence& s);

    //@}

    /**
     * @name absolute
     *
     * @brief Accessor and modifier functions for the %absolute
     * sequence element.
     *
     * Geometric transformation to set as the Object's graphic properties
     * state.
     */
    //@{

    /**
     * @brief Element type.
     */
    typedef ::aosl::Transformation AbsoluteType;

    /**
     * @brief Element sequence container type.
     */
    typedef ::xsd::cxx::tree::sequence< AbsoluteType > AbsoluteSequence;

    /**
     * @brief Element iterator type.
     */
    typedef AbsoluteSequence::iterator AbsoluteIterator;

    /**
     * @brief Element constant iterator type.
     */
    typedef AbsoluteSequence::const_iterator AbsoluteConstIterator;

    /**
     * @brief Element traits type.
     */
    typedef ::xsd::cxx::tree::traits< AbsoluteType, char > AbsoluteTraits;

    /**
     * @brief Return a read-only (constant) reference to the element
     * sequence.
     *
     * @return A constant reference to the sequence container.
     */
    const AbsoluteSequence&
    absolute () const;

    /**
     * @brief Return a read-write reference to the element sequence.
     *
     * @return A reference to the sequence container.
     */
    AbsoluteSequence&
    absolute ();

    /**
     * @brief Copy elements from a given sequence.
     *
     * @param s A sequence to copy elements from.
     *
     * For each element in @a s this function makes a copy and adds it 
     * to the sequence. Note that this operation completely changes the 
     * sequence and all old elements will be lost.
     */
    void
    absolute (const AbsoluteSequence& s);

    //@}

    /**
     * @name Constructors
     */
    //@{

    /**
     * @brief Create an instance from the ultimate base and
     * initializers for required elements and attributes.
     */
    Change_transform (const ObjectType&);

    /**
     * @brief Create an instance from a DOM element.
     *
     * @param e A DOM element to extract the data from.
     * @param f Flags to create the new instance with.
     * @param c A pointer to the object that will contain the new
     * instance.
     */
    Change_transform (const ::xercesc::DOMElement& e,
                      ::xml_schema::Flags f = 0,
                      ::xml_schema::Container* c = 0);

    /**
     * @brief Copy constructor.
     *
     * @param x An instance to make a copy of.
     * @param f Flags to create the copy with.
     * @param c A pointer to the object that will contain the copy.
     *
     * For polymorphic object models use the @c _clone function instead.
     */
    Change_transform (const Change_transform& x,
                      ::xml_schema::Flags f = 0,
                      ::xml_schema::Container* c = 0);

    /**
     * @brief Copy the instance polymorphically.
     *
     * @param f Flags to create the copy with.
     * @param c A pointer to the object that will contain the copy.
     * @return A pointer to the dynamically allocated copy.
     *
     * This function ensures that the dynamic type of the instance is
     * used for copying and should be used for polymorphic object
     * models instead of the copy constructor.
     */
    virtual Change_transform*
    _clone (::xml_schema::Flags f = 0,
            ::xml_schema::Container* c = 0) const;

    //@}

    /**
     * @brief Destructor.
     */
    virtual 
    ~Change_transform ();

    // Implementation.
    //

    //@cond

    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::Flags);

    protected:
    RelativeSequence relative_;
    AbsoluteSequence absolute_;

    //@endcond
  };

  bool
  operator== (const Change_transform&, const Change_transform&);

  bool
  operator!= (const Change_transform&, const Change_transform&);
}

#ifndef XSD_DONT_INCLUDE_INLINE

#include "aosl/change.inl"

#include "aosl/transformation.hpp"
#include "aosl/transformation.inl"

#endif // XSD_DONT_INCLUDE_INLINE

#include <iosfwd>

namespace aosl
{
  ::std::ostream&
  operator<< (::std::ostream&, const Change_transform&);
}

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

namespace aosl
{
}

#include <iosfwd>

#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>
#include <xercesc/framework/XMLFormatter.hpp>

#include <xsd/cxx/xml/dom/auto-ptr.hxx>

namespace aosl
{
  void
  operator<< (::xercesc::DOMElement&, const Change_transform&);
}

#ifndef XSD_DONT_INCLUDE_INLINE
#include "aosl/change_transform.inl"
#endif // XSD_DONT_INCLUDE_INLINE

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // AOSLCPP_AOSL__CHANGE_TRANSFORM_HPP
