// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema
// to C++ data binding compiler, in the Proprietary License mode.
// You should have received a proprietary license from Code Synthesis
// Tools CC prior to generating this code. See the license text for
// conditions.
//

// Begin prologue.
//

#define AOSLCPP_SOURCE 

//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "aosl/event.hpp"

#include <xsd/cxx/xml/dom/wildcard-source.hxx>

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

#include <xsd/cxx/tree/comparison-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;

  static
  const ::xsd::cxx::tree::comparison_plate< 0, char >
  comparison_plate_init;
}

namespace aosl
{
  // Event
  //

  Event::
  Event (const MoveType& move)
  : ::xml_schema::Type (),
    move_ (move, ::xml_schema::Flags (), this)
  {
  }

  Event::
  Event (const Event& x,
         ::xml_schema::Flags f,
         ::xml_schema::Container* c)
  : ::xml_schema::Type (x, f, c),
    move_ (x.move_, f, this)
  {
  }

  Event::
  Event (const ::xercesc::DOMElement& e,
         ::xml_schema::Flags f,
         ::xml_schema::Container* c)
  : ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
    move_ (f, this)
  {
    if ((f & ::xml_schema::Flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, false, true);
      this->parse (p, f);
    }
  }

  void Event::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::Flags f)
  {
    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "move" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< MoveType > r (
          MoveTraits::create (i, f, this));

        this->move_.set (r);
        continue;
      }
    }

    if (!move_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "move",
        "");
    }
  }

  Event* Event::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class Event (*this, f, c);
  }

  Event::
  ~Event ()
  {
  }

  static
  const ::xsd::cxx::tree::type_factory_initializer< 0, char, Event >
  _xsd_Event_type_factory_init (
    "event",
    "artofsequence.org/aosl/1.0");

  static
  const ::xsd::cxx::tree::comparison_initializer< 0, char, Event >
  _xsd_Event_comparison_init;

  bool
  operator== (const Event& x, const Event& y)
  {
    if (!(x.move () == y.move ()))
      return false;

    return true;
  }

  bool
  operator!= (const Event& x, const Event& y)
  {
    return !(x == y);
  }
}

#include <ostream>

#include <xsd/cxx/tree/std-ostream-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::std_ostream_plate< 0, char >
  std_ostream_plate_init;
}

namespace aosl
{
  ::std::ostream&
  operator<< (::std::ostream& o, const Event& i)
  {
    o << ::std::endl << "move: " << i.move ();
    return o;
  }

  static
  const ::xsd::cxx::tree::std_ostream_initializer< 0, char, Event >
  _xsd_Event_std_ostream_init;
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace aosl
{
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

#include <xsd/cxx/tree/type-serializer-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_serializer_plate< 0, char >
  type_serializer_plate_init;
}

namespace aosl
{
  void
  operator<< (::xercesc::DOMElement& e, const Event& i)
  {
    e << static_cast< const ::xml_schema::Type& > (i);

    // move
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "move",
          e));

      a << i.move ();
    }
  }

  static
  const ::xsd::cxx::tree::type_serializer_initializer< 0, char, Event >
  _xsd_Event_type_serializer_init (
    "event",
    "artofsequence.org/aosl/1.0");
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

