// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema
// to C++ data binding compiler, in the Proprietary License mode.
// You should have received a proprietary license from Code Synthesis
// Tools CC prior to generating this code. See the license text for
// conditions.
//

// Begin prologue.
//

#define AOSLCPP_SOURCE 

//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "aosl/meta.hpp"

#include <xsd/cxx/xml/dom/wildcard-source.hxx>

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

#include <xsd/cxx/tree/comparison-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;

  static
  const ::xsd::cxx::tree::comparison_plate< 0, char >
  comparison_plate_init;
}

namespace aosl
{
  // Meta
  //

  Meta::
  Meta ()
  : ::xml_schema::Type (),
    version_ (::xml_schema::Flags (), this),
    authors_ (::xml_schema::Flags (), this),
    description_ (::xml_schema::Flags (), this),
    website_ (::xml_schema::Flags (), this),
    licence_ (::xml_schema::Flags (), this),
    targets_ (::xml_schema::Flags (), this),
    infos_ (::xml_schema::Flags (), this)
  {
  }

  Meta::
  Meta (const Meta& x,
        ::xml_schema::Flags f,
        ::xml_schema::Container* c)
  : ::xml_schema::Type (x, f, c),
    version_ (x.version_, f, this),
    authors_ (x.authors_, f, this),
    description_ (x.description_, f, this),
    website_ (x.website_, f, this),
    licence_ (x.licence_, f, this),
    targets_ (x.targets_, f, this),
    infos_ (x.infos_, f, this)
  {
  }

  Meta::
  Meta (const ::xercesc::DOMElement& e,
        ::xml_schema::Flags f,
        ::xml_schema::Container* c)
  : ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
    version_ (f, this),
    authors_ (f, this),
    description_ (f, this),
    website_ (f, this),
    licence_ (f, this),
    targets_ (f, this),
    infos_ (f, this)
  {
    if ((f & ::xml_schema::Flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false);
      this->parse (p, f);
    }
  }

  void Meta::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::Flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // version
      //
      if (n.name () == "version" && n.namespace_ () == "artofsequence.org/aosl/1.0")
      {
        ::std::auto_ptr< VersionType > r (
          VersionTraits::create (i, f, this));

        if (!this->version_)
        {
          this->version_.set (r);
          continue;
        }
      }

      // authors
      //
      if (n.name () == "authors" && n.namespace_ () == "artofsequence.org/aosl/1.0")
      {
        ::std::auto_ptr< AuthorsType > r (
          AuthorsTraits::create (i, f, this));

        if (!this->authors_)
        {
          this->authors_.set (r);
          continue;
        }
      }

      // description
      //
      if (n.name () == "description" && n.namespace_ () == "artofsequence.org/aosl/1.0")
      {
        ::std::auto_ptr< DescriptionType > r (
          DescriptionTraits::create (i, f, this));

        if (!this->description_)
        {
          this->description_.set (r);
          continue;
        }
      }

      // website
      //
      if (n.name () == "website" && n.namespace_ () == "artofsequence.org/aosl/1.0")
      {
        ::std::auto_ptr< WebsiteType > r (
          WebsiteTraits::create (i, f, this));

        if (!this->website_)
        {
          this->website_.set (r);
          continue;
        }
      }

      // licence
      //
      if (n.name () == "licence" && n.namespace_ () == "artofsequence.org/aosl/1.0")
      {
        ::std::auto_ptr< LicenceType > r (
          LicenceTraits::create (i, f, this));

        if (!this->licence_)
        {
          this->licence_.set (r);
          continue;
        }
      }

      // targets
      //
      if (n.name () == "targets" && n.namespace_ () == "artofsequence.org/aosl/1.0")
      {
        ::std::auto_ptr< TargetsType > r (
          TargetsTraits::create (i, f, this));

        if (!this->targets_)
        {
          this->targets_.set (r);
          continue;
        }
      }

      // infos
      //
      if (n.name () == "infos" && n.namespace_ () == "artofsequence.org/aosl/1.0")
      {
        ::std::auto_ptr< InfosType > r (
          InfosTraits::create (i, f, this));

        if (!this->infos_)
        {
          this->infos_.set (r);
          continue;
        }
      }

      break;
    }
  }

  Meta* Meta::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class Meta (*this, f, c);
  }

  Meta::
  ~Meta ()
  {
  }

  bool
  operator== (const Meta& x, const Meta& y)
  {
    if (!(x.version () == y.version ()))
      return false;

    if (!(x.authors () == y.authors ()))
      return false;

    if (!(x.description () == y.description ()))
      return false;

    if (!(x.website () == y.website ()))
      return false;

    if (!(x.licence () == y.licence ()))
      return false;

    if (!(x.targets () == y.targets ()))
      return false;

    if (!(x.infos () == y.infos ()))
      return false;

    return true;
  }

  bool
  operator!= (const Meta& x, const Meta& y)
  {
    return !(x == y);
  }
}

#include <ostream>

#include <xsd/cxx/tree/std-ostream-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::std_ostream_plate< 0, char >
  std_ostream_plate_init;
}

namespace aosl
{
  ::std::ostream&
  operator<< (::std::ostream& o, const Meta& i)
  {
    if (i.version ())
    {
      o << ::std::endl << "version: " << *i.version ();
    }

    if (i.authors ())
    {
      o << ::std::endl << "authors: " << *i.authors ();
    }

    if (i.description ())
    {
      o << ::std::endl << "description: " << *i.description ();
    }

    if (i.website ())
    {
      o << ::std::endl << "website: " << *i.website ();
    }

    if (i.licence ())
    {
      o << ::std::endl << "licence: " << *i.licence ();
    }

    if (i.targets ())
    {
      o << ::std::endl << "targets: " << *i.targets ();
    }

    if (i.infos ())
    {
      o << ::std::endl << "infos: " << *i.infos ();
    }

    return o;
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace aosl
{
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

#include <xsd/cxx/tree/type-serializer-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_serializer_plate< 0, char >
  type_serializer_plate_init;
}

namespace aosl
{
  void
  operator<< (::xercesc::DOMElement& e, const Meta& i)
  {
    e << static_cast< const ::xml_schema::Type& > (i);

    // version
    //
    if (i.version ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "version",
          "artofsequence.org/aosl/1.0",
          e));

      s << *i.version ();
    }

    // authors
    //
    if (i.authors ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "authors",
          "artofsequence.org/aosl/1.0",
          e));

      s << *i.authors ();
    }

    // description
    //
    if (i.description ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "description",
          "artofsequence.org/aosl/1.0",
          e));

      s << *i.description ();
    }

    // website
    //
    if (i.website ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "website",
          "artofsequence.org/aosl/1.0",
          e));

      s << *i.website ();
    }

    // licence
    //
    if (i.licence ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "licence",
          "artofsequence.org/aosl/1.0",
          e));

      s << *i.licence ();
    }

    // targets
    //
    if (i.targets ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "targets",
          "artofsequence.org/aosl/1.0",
          e));

      s << *i.targets ();
    }

    // infos
    //
    if (i.infos ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "infos",
          "artofsequence.org/aosl/1.0",
          e));

      s << *i.infos ();
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

